"""The compiled sidecar (``*.compiled.yaml``): derive path, load, write atomically.

It is generated fresh by ``compile`` (no comment round-trip to preserve), so it
is written with a plain YAML dump. ``compile`` never mutates the source scenario.
"""

from __future__ import annotations

import os
import tempfile
from pathlib import Path

from ruamel.yaml import YAML

from guidebot_recorder.models.compiled import CompiledScenario

_HEADER = "# GENERATED by `guidebot compile` — do not edit by hand.\n"
_SOURCE_SUFFIXES = (".scenario.yaml", ".scenario.yml", ".yaml", ".yml")


def compiled_path(source: Path | str) -> Path:
    """Derive the compiled sidecar path next to ``source``.

    ``login.scenario.yaml`` → ``login.compiled.yaml``; ``s.yaml`` → ``s.compiled.yaml``.
    """
    source = Path(source)
    name = source.name
    base = source.stem
    for suffix in _SOURCE_SUFFIXES:
        if name.endswith(suffix):
            base = name[: -len(suffix)]
            break
    return source.parent / f"{base}.compiled.yaml"


def load_compiled(path: Path | str) -> CompiledScenario:
    path = Path(path)
    yaml = YAML(typ="safe")
    data = yaml.load(path.read_text(encoding="utf-8"))
    _mark_missing_versions_as_legacy(data)
    return CompiledScenario.model_validate(data)


def _mark_missing_versions_as_legacy(data: object) -> None:
    """Keep parsing old sidecars without treating them as current artifacts.

    Pydantic defaults are convenient for constructing a new model in Python, but
    applying today's default to a version field omitted by an old YAML file would
    make the migration check ineffective.  Missing on-disk versions mean schema v1.
    """

    if not isinstance(data, dict):
        return
    data.setdefault("compiler_version", 1)
    actions = data.get("actions")
    if not isinstance(actions, list):
        return
    for action in actions:
        if not isinstance(action, dict):
            continue
        fingerprint = action.get("fingerprint")
        if isinstance(fingerprint, dict):
            fingerprint.setdefault("compiler_version", 1)


def write_compiled(path: Path | str, compiled: CompiledScenario) -> None:
    """Write ``compiled`` atomically (temp file beside target → os.replace)."""
    path = Path(path)
    payload = compiled.model_dump(by_alias=True, exclude_none=True)
    yaml = YAML()
    yaml.default_flow_style = False
    tmp: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as fh:
            tmp = Path(fh.name)
            fh.write(_HEADER)
            yaml.dump(payload, fh)
        os.replace(tmp, path)
    finally:
        if tmp is not None and tmp.exists():
            tmp.unlink(missing_ok=True)
