"""The compiled sidecar (``*.compiled.yaml``): derive path, load, write atomically.

It is generated fresh by ``compile`` (no comment round-trip to preserve), so it
is written with a plain YAML dump. ``compile`` never mutates the source scenario.
"""

from __future__ import annotations

import os
from pathlib import Path

from ruamel.yaml import YAML

from guidebot_recorder.models.compiled import CompiledScenario

_HEADER = "# GENERATED by `guidebot compile` — do not edit by hand.\n"
_SOURCE_SUFFIXES = (".scenario.yaml", ".scenario.yml", ".yaml", ".yml")


def compiled_path(source: Path | str) -> Path:
    """Derive the compiled sidecar path next to ``source``.

    ``login.scenario.yaml`` → ``login.compiled.yaml``; ``s.yaml`` → ``s.compiled.yaml``.
    """
    source = Path(source)
    name = source.name
    base = source.stem
    for suffix in _SOURCE_SUFFIXES:
        if name.endswith(suffix):
            base = name[: -len(suffix)]
            break
    return source.parent / f"{base}.compiled.yaml"


def load_compiled(path: Path | str) -> CompiledScenario:
    path = Path(path)
    yaml = YAML(typ="safe")
    data = yaml.load(path.read_text(encoding="utf-8"))
    return CompiledScenario.model_validate(data)


def write_compiled(path: Path | str, compiled: CompiledScenario) -> None:
    """Write ``compiled`` atomically (temp file beside target → os.replace)."""
    path = Path(path)
    payload = compiled.model_dump(by_alias=True, exclude_none=True)
    yaml = YAML()
    yaml.default_flow_style = False
    tmp = path.with_name(f".{path.name}.tmp")
    try:
        with tmp.open("w", encoding="utf-8") as fh:
            fh.write(_HEADER)
            yaml.dump(payload, fh)
        os.replace(tmp, path)
    finally:
        if tmp.exists():
            tmp.unlink(missing_ok=True)
