import pytest
from pydantic import ValidationError

from guidebot_recorder.models.action import (
    COMPILER_VERSION,
    CachedAction,
    Fingerprint,
    PendingAction,
)
from guidebot_recorder.models.compiled import CompiledScenario
from guidebot_recorder.models.identity import Identity
from guidebot_recorder.models.target import RoleTarget
from guidebot_recorder.scenario.compiled import compiled_path, load_compiled, write_compiled


def test_compiled_path_derivation(tmp_path):
    assert compiled_path(tmp_path / "login.scenario.yaml").name == "login.compiled.yaml"
    assert compiled_path(tmp_path / "s.yaml").name == "s.compiled.yaml"


def _action() -> CachedAction:
    return CachedAction(
        action="click",
        target=RoleTarget(role="button", name="Zaloguj"),
        identity=Identity(tag="button", ancestry_digest="d"),
        expect="navigation",
        fingerprint=Fingerprint(
            command_kind="teach",
            compiled_from="kliknij Zaloguj",
            expect="navigation",
            config_hash="c",
        ),
    )


def test_write_then_load_roundtrips(tmp_path):
    path = tmp_path / "login.compiled.yaml"
    compiled = CompiledScenario(source="login.scenario.yaml", actions=[None, _action(), None])

    write_compiled(path, compiled)
    loaded = load_compiled(path)

    assert loaded.source == "login.scenario.yaml"
    assert loaded.actions[0] is None
    assert loaded.actions[2] is None
    assert loaded.actions[1].target.name == "Zaloguj"
    assert loaded.actions[1].identity.tag == "button"


def test_write_is_generated_header(tmp_path):
    path = tmp_path / "s.compiled.yaml"
    write_compiled(path, CompiledScenario(source="s.yaml", actions=[None]))
    assert path.read_text(encoding="utf-8").startswith("# GENERATED by")


def test_write_does_not_follow_predictable_temporary_symlink(tmp_path):
    path = tmp_path / "login.compiled.yaml"
    outside = tmp_path / "outside.txt"
    outside.write_text("sentinel", encoding="utf-8")
    predictable_tmp = tmp_path / ".login.compiled.yaml.tmp"
    predictable_tmp.symlink_to(outside)

    write_compiled(path, CompiledScenario(source="login.scenario.yaml", actions=[None]))

    assert outside.read_text(encoding="utf-8") == "sentinel"
    assert predictable_tmp.is_symlink()
    assert load_compiled(path).source == "login.scenario.yaml"


def test_load_missing_versions_marks_sidecar_as_legacy(tmp_path):
    path = tmp_path / "legacy.compiled.yaml"
    write_compiled(path, CompiledScenario(source="legacy.yaml", actions=[_action()]))
    without_versions = "\n".join(
        line
        for line in path.read_text(encoding="utf-8").splitlines()
        if "compiler_version:" not in line
    )
    path.write_text(without_versions + "\n", encoding="utf-8")

    loaded = load_compiled(path)

    assert loaded.compiler_version == 1 < COMPILER_VERSION
    assert loaded.actions[0].fingerprint.compiler_version == 1


def _fingerprint() -> Fingerprint:
    return Fingerprint(
        command_kind="wait",
        compiled_from="baner cookies",
        expect="none",
        config_hash="c",
        state="visible",
    )


def test_pending_action_defaults_and_forbids_extras():
    pending = PendingAction(fingerprint=_fingerprint())
    assert pending.pending is True

    with pytest.raises(ValidationError):
        PendingAction(fingerprint=_fingerprint(), bogus=1)


def test_pending_action_roundtrips_through_yaml(tmp_path):
    path = tmp_path / "opt.compiled.yaml"
    compiled = CompiledScenario(
        source="opt.scenario.yaml",
        actions=[None, PendingAction(fingerprint=_fingerprint()), _action()],
    )

    write_compiled(path, compiled)
    loaded = load_compiled(path)

    assert loaded.actions[0] is None
    assert isinstance(loaded.actions[1], PendingAction)
    assert loaded.actions[1].pending is True
    assert loaded.actions[1].fingerprint.compiled_from == "baner cookies"
    assert isinstance(loaded.actions[2], CachedAction)
    assert loaded.actions[2].target.name == "Zaloguj"


def test_pending_entry_is_not_confused_with_a_cached_action(tmp_path):
    path = tmp_path / "opt.compiled.yaml"
    write_compiled(
        path,
        CompiledScenario(source="s.yaml", actions=[PendingAction(fingerprint=_fingerprint())]),
    )
    assert "pending: true" in path.read_text(encoding="utf-8")


def test_legacy_sidecar_without_pending_entries_still_loads(tmp_path):
    path = tmp_path / "legacy.compiled.yaml"
    write_compiled(path, CompiledScenario(source="legacy.yaml", actions=[None, _action()]))

    loaded = load_compiled(path)

    assert loaded.actions[0] is None
    assert isinstance(loaded.actions[1], CachedAction)
