from guidebot_recorder.models.action import CachedAction, Fingerprint
from guidebot_recorder.models.compiled import CompiledScenario
from guidebot_recorder.models.identity import Identity
from guidebot_recorder.models.target import RoleTarget
from guidebot_recorder.scenario.compiled import compiled_path, load_compiled, write_compiled


def test_compiled_path_derivation(tmp_path):
    assert compiled_path(tmp_path / "login.scenario.yaml").name == "login.compiled.yaml"
    assert compiled_path(tmp_path / "s.yaml").name == "s.compiled.yaml"


def _action() -> CachedAction:
    return CachedAction(
        action="click",
        target=RoleTarget(role="button", name="Zaloguj"),
        identity=Identity(tag="button", ancestry_digest="d"),
        expect="navigation",
        fingerprint=Fingerprint(
            command_kind="teach",
            compiled_from="kliknij Zaloguj",
            expect="navigation",
            config_hash="c",
        ),
    )


def test_write_then_load_roundtrips(tmp_path):
    path = tmp_path / "login.compiled.yaml"
    compiled = CompiledScenario(source="login.scenario.yaml", actions=[None, _action(), None])

    write_compiled(path, compiled)
    loaded = load_compiled(path)

    assert loaded.source == "login.scenario.yaml"
    assert loaded.actions[0] is None
    assert loaded.actions[2] is None
    assert loaded.actions[1].target.name == "Zaloguj"
    assert loaded.actions[1].identity.tag == "button"


def test_write_is_generated_header(tmp_path):
    path = tmp_path / "s.compiled.yaml"
    write_compiled(path, CompiledScenario(source="s.yaml", actions=[None]))
    assert path.read_text(encoding="utf-8").startswith("# GENERATED by")
